In [1]:
import pandas as pd

In [11]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic (2).csv

In [90]:
#Task 0 open data/titanic.csv
df = pd.read_csv('titanic.csv', engine = "python")
#df = pd.read_csv("https://raw.githubusercontent.com/CBP-DS/ds_intensive_course/main/data/titanic.csv?token=GHSAT0AAAAAACJTPLIL5TGN4SIHQ6VARBWOZKDLMNA")

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
#Task 1 how many passangers are in the data?
print(df.PassengerId.nunique())
print(len(df.PassengerId.unique()))

891
891

In [30]:
df.Name.str[0]

0      B
1      C
2      H
3      F
4      A
      ..
886    M
887    G
888    J
889    B
890    D
Name: Name, Length: 891, dtype: object

In [32]:
#Task 2 How many distinct Surnames can you see in the data?

splitted_names = df.Name.str.split(",")
splitted_names

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

In [33]:
splitted_names = splitted_names.str[0]
splitted_names

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

In [34]:
print(splitted_names.nunique())

667

In [36]:
#Task 3 sum Fare per A) location of Embarked B) Locatio of Embarked and Sex
#result should be dataframe

gr = df.groupby(["Embarked"], as_index = False).Fare.sum()
print(gr, "\n", type(gr))

  Embarked        Fare
0        C  10072.2962
1        Q   1022.2543
2        S  17439.3988
 <class 'pandas.core.frame.DataFrame'>

In [43]:
gr = df.groupby(["Embarked"])["Fare"].sum()
print(gr, "\n", type(gr))

Embarked
C    10072.2962
Q     1022.2543
S    17439.3988
Name: Fare, dtype: float64
 <class 'pandas.core.series.Series'>

In [44]:
gr = df.groupby(["Embarked", "Sex"], as_index = False).Fare.sum()
print(gr, "\n", type(gr))

  Embarked     Sex       Fare
0        C  female  5487.3958
1        C    male  4584.9004
2        Q  female   454.8585
3        Q    male   567.3958
4        S  female  7864.4085
5        S    male  9574.9903
 <class 'pandas.core.frame.DataFrame'>

In [45]:
gr = df.groupby(["Embarked", "Sex"], as_index = False)["Fare", "PassengerId"].sum()
print(gr, "\n", type(gr))

  Embarked     Sex       Fare  PassengerId
0        C  female  5487.3958        31924
1        C    male  4584.9004        42896
2        Q  female   454.8585        13469
3        Q    male   567.3958        18709
4        S  female  7864.4085        89058
5        S    male  9574.9903       200438
 <class 'pandas.core.frame.DataFrame'>

<ipython-input-45-07e09025ed9f>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  gr = df.groupby(["Embarked", "Sex"], as_index = False)["Fare", "PassengerId"].sum()

In [52]:
#Task 4 How wold you drop all rows that contain none? How about dropping rows that have none in Cabin?
print(len(df))
no_nan = df.dropna()
print(len(no_nan))

891
183

In [53]:
print(len(df))
no_nan_cabin = df.dropna(subset = ["Cabin"])
print(len(no_nan_cabin))

891
204

In [ ]:
#Task 5 Use columns SibSp and Parch to form binary attribute has_family (use max or addition of two columns)

In [58]:
df["SibSp"].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [59]:
df["Parch"].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [71]:
df["has_family"] = df["SibSp"].values + df["Parch"].values

In [72]:
filter = df["has_family"]>1
df[filter]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,has_family
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,4
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,2
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,2
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,6
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,2
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,2
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,5
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3

In [68]:
df.loc[filter, "has_family"] = 1
print(df["has_family"].unique())

[1 0]

In [61]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,has_family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [79]:
#Task 6 drop column has family
df = df.drop("has_family", axis = 1)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [78]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,has_family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [91]:
#Task 7 Use conditions approach to form has_family attriubte

filter = (df["SibSp"]>0) | (df["Parch"]>0)
df["has_family"] = 0
df.loc[filter, "has_family"] = 1

In [87]:
columns_to_keep = df.columns[2:7]

In [ ]:
df[df.columns[:-1]]

In [88]:
df = df[columns_to_keep]

In [89]:
df

,Pclass,Name,Sex,Age,SibSp
0,3,"Braund, Mr. Owen Harris",male,22.0,1
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1
4,3,"Allen, Mr. William Henry",male,35.0,0
...,...,...,...,...,...
886,2,"Montvila, Rev. Juozas",male,27.0,0
887,1,"Graham, Miss. Margaret Edith",female,19.0,0
888,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1
889,1,"Behr, Mr. Karl Howell",male,26.0,0
890,3,"Dooley, Mr. Patrick",male,32.0,0

In [93]:
#Task 8 What is the overall age average? What is the age average for women? And for men?
print(df["Age"].mean())
df.groupby(["Sex"])["Age"].mean()

29.69911764705882

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [94]:
#Task 9 how many passerngers traveled on their own (alone)?

all_passengers = df['PassengerId'].nunique()
print(all_passengers)
hasfamily_passengers = df["has_family"].sum()
print(hasfamily_passengers)


alone = all_passengers - hasfamily_passengers
print(alone)

891
354
537

In [95]:
filter = df["has_family"] == 0
df[filter]["PassengerId"].nunique()

537

In [97]:
df["Fare"]

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [98]:
df["different fare"] = 239240

In [99]:
df["different fare"]

0      239240
1      239240
2      239240
3      239240
4      239240
        ...
886    239240
887    239240
888    239240
889    239240
890    239240
Name: different fare, Length: 891, dtype: int64

In [101]:
filter = df["has_family"] <1
filter

0      False
1      False
2       True
3      False
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: has_family, Length: 891, dtype: bool

In [102]:
print("This is the number of loners:", filter.sum())

This is the number of loners: 537

In [104]:
df = df.drop_duplicates()

In [110]:
#Task 10 is there any effect of class passengers traveled in and survival rate?
df["Pclass"].unique()

df.groupby(["Pclass"])["Cabin"].agg(Nunique='nunique', Count='count')

        Nunique  Count
Pclass
1           133    176
2             7     16
3             7     12

In [113]:
df_filled = df.copy()
df_filled["Cabin"] = df_filled["Cabin"].fillna("unknown")
df_filled.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,has_family,different fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,unknown,S,1,239240
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,239240

In [114]:
df.groupby(["Pclass"])["Survived"].agg(Count='count', Sum='sum')

        Count  Sum
Pclass
1         216  136
2         184   87
3         491  119

In [115]:
_ = df.groupby(["Pclass"])["Survived"].agg(Count='count', Sum='sum')
_["ratio"] = _["Sum"]/_["Count"]
_

        Count  Sum     ratio
Pclass
1         216  136  0.629630
2         184   87  0.472826
3         491  119  0.242363

In [119]:
#Task 11 Do missing cabin values have something incommon with Pclass?
df_filled.groupby(["Pclass"])["Cabin"].agg(Nunique='nunique', Count='count')

        Nunique  Count
Pclass
1           134    216
2             8    184
3             8    491

In [120]:
#Task 12 Create new column family name, count members of the family in data
df["family_name"] = df["Name"].str.split(",").str[0]
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,has_family,different fare,family_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,239240,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,239240,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,239240,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,239240,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,239240,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,239240,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,239240,Graham
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1,239240,Johnston
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,239240,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,239240,Dooley

In [121]:
df.groupby(["family_name"])["PassengerId"].count()

family_name
Abbing           1
Abbott           2
Abelson          2
Adahl            1
Adams            1
                ..
de Mulder        1
de Pelsmaeker    1
del Carlo        1
van Billiard     1
van Melkebeke    1
Name: PassengerId, Length: 667, dtype: int64

In [123]:
mapping = df['family_name'].value_counts()
print(mapping)

Andersson    9
Sage         7
Panula       6
Skoog        6
Carter       6
            ..
Hanna        1
Lewy         1
Mineff       1
Haas         1
Dooley       1
Name: family_name, Length: 667, dtype: int64

In [135]:
_ = mapping.to_frame()
_ = _.reset_index()
_.columns = ["family_name", "freq"]
_

    family_name  freq
0     Andersson     9
1          Sage     7
2        Panula     6
3         Skoog     6
4        Carter     6
..          ...   ...
662       Hanna     1
663        Lewy     1
664      Mineff     1
665        Haas     1
666      Dooley     1

[667 rows x 2 columns]

In [136]:
pd.merge(df, _, on = "family_name", how = "inner")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,has_family,different fare,family_name,family_name_freq,family_size,freq
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,239240,Braund,2,2,2
1,478,0,3,"Braund, Mr. Lewis Richard",male,29.0,1,0,3460,7.0458,NaN,S,1,239240,Braund,2,2,2
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,239240,Cumings,1,1,1
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,239240,Heikkinen,1,1,1
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,239240,Futrelle,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,0,239240,Banfield,1,1,1
887,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,0,239240,Sutehall,1,1,1
888,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,239240,Montvila,1,1,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,239240,Behr,1,1,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,239240,Dooley,1,1,1

In [124]:
df["family_name_freq"] = df['family_name'].map(mapping)

In [125]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,has_family,different fare,family_name,family_name_freq
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1,239240,Braund,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,239240,Cumings,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,239240,Heikkinen,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,239240,Futrelle,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,239240,Allen,2

In [128]:
df["family_size"] = df.family_name_freq.values

In [131]:
df.loc[((df.has_family == 0)&(df.family_name_freq > 1)), "family_size"] = 1

df.groupby(["family_name", "family_size"])["PassengerId"].count()

family_name    family_size
Abbing         1              1
Abbott         2              2
Abelson        2              2
Adahl          1              1
Adams          1              1
                             ..
de Mulder      1              1
de Pelsmaeker  1              1
del Carlo      1              1
van Billiard   1              1
van Melkebeke  1              1
Name: PassengerId, Length: 689, dtype: int64

In [ ]:
#Task 13 group Fare by 3 thresholds so you have category cheap fare, regular fare, expensive fare

In [ ]:
#Task 14 form an empty dataset, append counts in fare category to it

In [137]:
empty_df = pd.DataFrame({})
empty_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
#Task 15 rename column PassengerId in appended dataframe to Passenger Count